all_options = {
    'Andorra 🇦🇩': ['Pal Arinsal'],
    'Argentina 🇦🇷': ['Buenos Aires'],
    'Austria 🇦🇹': ['Dornbirn', 'Innsbruck', 'St. Anton', 'Vienna'],
    'Bahamas 🇧🇸': ['Eleuthera', 'New Providence Island (where Nassau is located)'],
    'Belgium 🇧🇪': ['Antwerp', 'Brussels', 'Ghent', 'Leuven'],
    'Bolivia 🇧🇴': ['Cliza', 'Cochabamba'],
    'Bosnia & Herzegovina 🇧🇦': ['Medjugorje', 'Mostar'],
    'Bulgaria 🇧🇬': ['Sofia', 'Varna'],
    'Canada 🇨🇦': ['Banff', 'Calgary'],
    'Chile 🇨🇱': ['Puerto Natales (Patagonia)', 'Santiago', 'Torres del Paine NP (Patagonia)', 'Valle Nevado',
                 'Valparaíso / Viña del Mar'],
    'Croatia 🇭🇷': ['Dubrovnik', 'Motovun', 'Opatija', 'Plitvice Lakes National Park', 'Pula', 'Rovinj',
                   'Vodnjan', 'Zagreb'],
    'Czechia 🇨🇿': ['Prague'],
    'Denmark 🇩🇰': ['Copenhagen'],
    'Ecuador 🇪🇨': ['Galapagos Islands', 'Quito'],
    'England 🏴󠁧󠁢󠁥󠁮󠁧󠁿': ['London'],
    'France 🇫🇷': ['Colmar', 'Paris', 'Strasbourg'],
    'Germany 🇩🇪': ['Berlin', 'Cologne', 'Düsseldorf', 'Dortmund', 'Dresden', 'Flensburg', 'Gengenbach', 'Hamburg',
                   'Kiel', 'Lübeck',
                   'Leipzig', 'Munich', 'Nuremberg', 'Oranienburg', 'Potsdam', 'Rügen', 'Stralsund', 'Stuttgart'],
    'Hungary 🇭🇺': ['Budapest'],
    'Iceland 🇮🇸': ['Reykjavik', 'Southern half of island'],
    'Ireland 🇮🇪': ['Cliffs of Moher', 'Dingle', 'Dublin', 'Tralee'],
    'Italy 🇮🇹': ['Bergamo', 'Florence', 'Genoa', 'Lecco', 'Milan', 'Portofino', 'Rome', 'Vatican 🇻🇦', 'Venice',
                 'Verona'],
    'Mexico 🇲🇽': ['Cancún', 'Mexico City'],
    'Montenegro 🇲🇪': ['Kotor'],
    'Morocco 🇲🇦': ['Tangier'],
    'Netherlands 🇳🇱': ['Amsterdam'],
    'North Macedonia 🇲🇰': ['Skopje'],
    'Norway 🇳🇴': ['Oslo'],
    'Peru 🇵🇪': ['Lima', 'Iquitos'],
    'Poland 🇵🇱': ['Krakow', 'Wrocław'],
    'Portugal 🇵🇹': ['Guincho Beach', 'Lisbon'],
    'Puerto Rico 🇵🇷': ['Rincón', 'San Juan'],
    'Slovakia 🇸🇰': ['Bratislava'],
    'Slovenia 🇸🇮': ['Ljubljana'],
    'Spain 🇪🇸': ['Azpeitia', 'Barcelona', 'Begur', 'Bilbao', 'Buñol', 'Córdoba', 'El Escorial', 'Girona', 'Granada',
                 'Irún', 'Jaén', 'Madrid', 'Málaga',
                 'Mallorca', 'Montserrat', 'Pineda de Mar', 'San Sebastián', 'Sitges', 'Segovia', 'Sevilla', 'Tenerife',
                 'Toledo', 'Valencia', 'Vilanova'],
    'Sweden 🇸🇪': ['Stockholm'],
    'Turkey 🇹🇷': ['Istanbul'],
    # 'USA 🇺🇸': ['Arizona', 'California', 'Colorado', 'DC', 'Florida', 'Illinois', 'Indiana', 'Iowa', 'Kentucky',
    #            'Maine',v'Massachusetts', 'Michigan', 'Missouri', 'Montana', 'Nebraska', 'New Hampshire', 'New York',
    #            'North Carolina', 'Ohio', 'Pennsylvania', 'Tennessee', 'Utah', 'Vermont', 'West Virginia', 'Wisconsin',
    #            'West Virginia'],
    'USA 🇺🇸': ['Bonneville Salt Flats', 'Boston', 'Champaign', 'Chicago', 'Copper Mountain', 'Dayton', 'Dubuque',
               'Miami', 'Missoula', 'Milwaukee',
               'NYC', 'San Francisco', 'Seattle', 'Zion National Park'],
}
